# This file stores configuration for your Shopify app.

scopes = "read_products,write_products,read_customers,write_customers,read_orders,write_orders,read_discounts,write_discounts,read_price_rules,write_price_rules,read_script_tags,write_script_tags"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://shopify-loyalty-app-1.onrender.com/auth/callback",
  "http://localhost:3000/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "https://fd5qw2-j9.myshopify.com"
include_config_on_deploy = true

[app_preferences]
url = "https://shopify-loyalty-app-1.onrender.com"